### PR TITLE
Corrects issue #14 

### PR DESCRIPTION
**Pull request by digitaltouch**
Send all "failed" events back through offlineHandle method. 
Updated Newtonsoft.Json to latest version 7.01.
Added lock to AsynEmitter flush method to stop random concurrency issues.
Tested additions with 4,500,000 events through the CloudFront collector.  MSMQ is functioning as expected.
Currently using in production environment.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks so much! Have you signed our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by digitaltouch** [comment]
@alexanderdean Just completed.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by fblundun** [comment]
Thanks @digitaltouch ! Just one thing - if an attempted http request fails with a `WebException` (perhaps due to being unable to connect) and doesn't have a status code, then each event in it will be added to the MSMQ queue [here](https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/eae2e6284c2d5055c20da8755ff0376f8e559e06/Snowplow.Tracker/Emitters/Emitter.cs#L354) (in the case of GET) or [here](https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/eae2e6284c2d5055c20da8755ff0376f8e559e06/Snowplow.Tracker/Emitters/Emitter.cs#L322) or [here](https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/eae2e6284c2d5055c20da8755ff0376f8e559e06/Snowplow.Tracker/Emitters/Emitter.csL307) (in the case of POST).

But those events will also be added to the queue [here](https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/eae2e6284c2d5055c20da8755ff0376f8e559e06/Snowplow.Tracker/Emitters/Emitter.cs#L242) (GET) or [here](https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/eae2e6284c2d5055c20da8755ff0376f8e559e06/Snowplow.Tracker/Emitters/Emitter.cs#L215) (POST). So in the case of WebException each event will be added to the queue twice instead of once.

It seems to me that we should get rid of those original calls to `offlineHandle` so that only your new ones remain - what do you think?

**Comment by digitaltouch** [comment]
@fblundun Good catch... I guess I wouldn't have seen this in testing due to the rare occurrence when Cloudfront doesn't respond.  Speaking of test - I was having issues getting the unit test to load properly.  I will spend some time with that in my local solution.

**Comment by fblundun** [comment]
Looks good! I've just run the unit tests on this PR and they all pass. What was going wrong with the tests for you locally?

**Comment by digitaltouch** [comment]
Trouble getting all the references to load correct in VS 2013.

**Comment by paulboocock** [comment]
Thanks for this PR from all those years ago! There's a few conflict with this PR as the dotnet tracker has seen some updates since the PR. I'm going to close this as we are looking at continuing to improve and move this tracker forward now but I'll be sure to make sure we don't see any concurrency issues which we may have seen in earlier versions. Apologies for not approving and merging this PR when it was originally opened.

**Pull request closed without merging**
